package lox;

public enum TokenType {

	// Single-character tokens.
	LEFT_PARENTHESIS, RIGHT_PARENTHESIS, LEFT_BRACE, RIGHT_BRACE,
	COMMA, MINUS, PLUS, SEMICOLON, SLASH, STAR,
	
	// One or two character tokens.
	BANG, BANG_EQUAL,
	EQUAL, EQUAL_EQUAL,
	GREATER, GREATER_EQUAL,
	LESS, LESS_EQUAL,
	
	// Literals.
	IDENTIFIER, STRING, NUMBER,
	
	// Keywords.
	AND, CLASS, ELSE, FALSE, FUNCTION, FOR, IF, NIL, OR,
	PRINT, RETURN, SUPER, THIS, TRUE, VAR, WHILE,
	
	EOF
	
}
